spring.application.name=loginPage

spring.data.mongodb.uri=mongodb://localhost:27017/testing-app
server.port=8282

# For logging
logging.level.org.springframework=INFO

# JWT Secret Key
jwt.secretKey= myKeys